name: stock_ml_inference
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pip
  - python=3.11
  - pylint
  - pip:
      - -r requirements.txt # use pip libraries for lightweight deployment (no conda install required)
      - -e . # allow to import local modules while editing them
